// This file is auto-generated by @hey-api/openapi-ts

export type Error = string | {
    [key: string]: unknown;
};

export type MetaInformation = {
    /**
     * Meta information about the CodeSandbox API
     */
    api: {
        latest_version: string;
        name: string;
    };
    /**
     * Meta information about the current authentication context
     */
    auth?: {
        scopes: Array<(string)>;
        team: (string) | null;
        version: string;
    };
};

export type Response = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
};

export type SandboxCreateRequest = {
    /**
     * Optional text description of the sandbox. Defaults to no description.
     */
    description?: string;
    /**
     * Filename of the entrypoint of the sandbox.
     */
    entry?: string;
    /**
     * Array of strings with external resources to load.
     */
    external_resources?: Array<(string)>;
    /**
     * Map of `path => file` where each file is a map.
     */
    files: {
        [key: string]: {
            /**
             * If the file has binary (non plain-text) contents, place the base-64 encoded contents in this key. Should be empty or missing if `is_binary` is `false`.
             */
            binary_content?: string;
            /**
             * If the file is non-binary in nature, place the (escaped) plain text contents in this key. Should be empty or missing if `is_binary` is `true`.
             */
            code?: string;
            /**
             * Whether the file contains binary contents.
             */
            is_binary?: boolean;
        };
    };
    /**
     * Whether changes to the sandbox are disallowed. Defaults to `false`.
     */
    is_frozen?: boolean;
    /**
     * Map of dependencies and their version specifications.
     */
    npm_dependencies?: {
        [key: string]: (string);
    };
    /**
     * Path to the collection where the new sandbox should be stored. Defaults to "/". If no collection exists at the given path, it will be created.
     */
    path?: string;
    /**
     * 0 for public, 1 for unlisted, and 2 for private. Privacy is subject to certain restrictions (team minimum setting, drafts must be private, etc.). Defaults to public.
     */
    privacy?: number;
    /**
     * Runtime to use for the sandbox. Defaults to `"browser"`.
     */
    runtime?: 'browser' | 'vm';
    /**
     * List of string tags to apply to the sandbox. Only the first ten will be used. Defaults to no tags.
     */
    tags?: Array<(string)>;
    /**
     * Name of the template from which the sandbox is derived (for example, `"static"`).
     */
    template?: string;
    /**
     * Sandbox title. Maximum 255 characters. Defaults to no title.
     */
    title?: string;
};

/**
 * Runtime to use for the sandbox. Defaults to `"browser"`.
 */
export type runtime = 'browser' | 'vm';

export type SandboxCreateResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        alias: string;
        id: string;
        title: (string) | null;
    };
};

export type SandboxForkRequest = {
    /**
     * Sandbox description. Maximum 255 characters. Defaults to description of original sandbox.
     */
    description?: string;
    /**
     * Sandbox frozen status. When true, edits to the sandbox are restricted. Defaults to frozen status of the original sandbox.
     */
    is_frozen?: boolean;
    /**
     * Path to the collection where the new sandbox should be stored. Defaults to "/". If no collection exists at the given path, it will be created.
     */
    path?: string;
    /**
     * Sandbox privacy. 0 for public, 1 for unlisted, and 2 for private. Subject to the minimum privacy restrictions of the workspace. Defaults to the privacy of the original sandbox.
     */
    privacy?: number;
    /**
     * Optional VM start configuration. If provided, the sandbox VM will be started immediately after creation.
     */
    start_options?: {
        /**
         * The time in seconds after which the VM will hibernate due to inactivity.
         * Must be a positive integer between 1 and 86400 (24 hours).
         * Defaults to 300 seconds (5 minutes) if not specified.
         *
         */
        hibernation_timeout_seconds?: number;
        /**
         * This determines in which cluster, closest to the given country the VM will be started in. The format is ISO-3166-1 alpha-2. If not set, the VM will be started closest to the caller of this API. This will only be applied when a VM is run for the first time, and will only serve as a hint (e.g. if the template of this sandbox runs in EU cluster, this sandbox will also run in the EU cluster).
         */
        ipcountry?: string;
        /**
         * Determines which specs to start the VM with. If not specified, the VM will start with the default specs for the workspace.
         *
         * You can only specify a VM tier when starting a VM that is inside your workspace. Specifying a VM tier for someone else's sandbox will return an error.
         *
         * Not all tiers will be available depending on the workspace subscription status, and higher tiers incur higher costs. Please see codesandbox.io/pricing for details on specs and costs.
         *
         */
        tier?: 'Pico' | 'Nano' | 'Micro' | 'Small' | 'Medium' | 'Large' | 'XLarge';
    };
    /**
     * Tags to set on the new sandbox, if any. Will not inherit tags from the source sandbox.
     */
    tags?: Array<(string)>;
    /**
     * Sandbox title. Maximum 255 characters. Defaults to title of original sandbox with (forked).
     */
    title?: string;
};

/**
 * Determines which specs to start the VM with. If not specified, the VM will start with the default specs for the workspace.
 *
 * You can only specify a VM tier when starting a VM that is inside your workspace. Specifying a VM tier for someone else's sandbox will return an error.
 *
 * Not all tiers will be available depending on the workspace subscription status, and higher tiers incur higher costs. Please see codesandbox.io/pricing for details on specs and costs.
 *
 */
export type tier = 'Pico' | 'Nano' | 'Micro' | 'Small' | 'Medium' | 'Large' | 'XLarge';

export type SandboxForkResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        alias: string;
        id: string;
        /**
         * VM start response. Only present when start_options were provided in the request.
         */
        start_response?: {
            bootup_type: string;
            cluster: string;
            id: string;
            latest_pitcher_version: string;
            pitcher_manager_version: string;
            pitcher_token: string;
            pitcher_url: string;
            pitcher_version: string;
            reconnect_token: string;
            user_workspace_path: string;
            workspace_path: string;
        } | null;
        title: (string) | null;
    };
};

export type SandboxGetResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        created_at: string;
        description?: (string) | null;
        id: string;
        is_frozen: boolean;
        privacy: number;
        tags: Array<(string)>;
        title?: (string) | null;
        updated_at: string;
    };
};

export type SandboxListResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        sandboxes: Array<{
            created_at: string;
            description?: (string) | null;
            id: string;
            is_frozen: boolean;
            privacy: number;
            tags: Array<(string)>;
            title?: (string) | null;
            updated_at: string;
        }>;
    };
};

export type TokenCreateRequest = {
    /**
     * API Version to use, formatted as YYYY-MM-DD. Defaults to the latest version at time of creation.
     */
    default_version?: (string) | null;
    /**
     * Description of this token, for instance where it will be used.
     */
    description?: string;
    /**
     * UTC Timestamp until when this token is valid. Omitting this field will create a token without an expiry.
     */
    expires_at?: (string) | null;
    /**
     * Which scopes to grant this token. The given scopes will replace the current scopes, revoking any that are no longer present in the list.
     */
    scopes?: Array<('sandbox_create' | 'sandbox_edit_code' | 'sandbox_read' | 'vm_manage')>;
};

export type TokenCreateResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        description: (string) | null;
        expires_at: (string) | null;
        scopes: Array<(string)>;
        team_id: string;
        token: string;
        token_id: string;
    };
};

/**
 * Updateable fields for API Tokens. Omitting a field will not update it; explicitly passing null or an empty list will clear the value.
 */
export type TokenUpdateRequest = {
    /**
     * API Version to use, formatted as YYYY-MM-DD
     */
    default_version?: (string) | null;
    /**
     * Description of this token, for instance where it will be used.
     */
    description?: (string) | null;
    /**
     * Expiry time of this token. Cannot be set in the past, and cannot be changed for tokens that have already expired. Pass null to make this token never expire.
     */
    expires_at?: (string) | null;
    /**
     * Which scopes to grant this token. The given scopes will replace the current scopes, revoking any that are no longer present in the list.
     */
    scopes?: Array<('sandbox_create' | 'sandbox_edit_code' | 'sandbox_read' | 'vm_manage')>;
};

export type TokenUpdateResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        description: (string) | null;
        expires_at?: (string) | null;
        scopes: Array<(string)>;
        team_id: string;
        token_id: string;
    };
};

export type VMHibernateRequest = {
    [key: string]: unknown;
};

export type VMHibernateResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        [key: string]: unknown;
    };
};

export type VMShutdownRequest = {
    [key: string]: unknown;
};

export type VMShutdownResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        [key: string]: unknown;
    };
};

export type VMStartRequest = {
    /**
     * The time in seconds after which the VM will hibernate due to inactivity.
     * Must be a positive integer between 1 and 86400 (24 hours).
     * Defaults to 300 seconds (5 minutes) if not specified.
     *
     */
    hibernation_timeout_seconds?: number;
    /**
     * This determines in which cluster, closest to the given country the VM will be started in. The format is ISO-3166-1 alpha-2. If not set, the VM will be started closest to the caller of this API. This will only be applied when a VM is run for the first time, and will only serve as a hint (e.g. if the template of this sandbox runs in EU cluster, this sandbox will also run in the EU cluster).
     */
    ipcountry?: string;
    /**
     * Determines which specs to start the VM with. If not specified, the VM will start with the default specs for the workspace.
     *
     * You can only specify a VM tier when starting a VM that is inside your workspace. Specifying a VM tier for someone else's sandbox will return an error.
     *
     * Not all tiers will be available depending on the workspace subscription status, and higher tiers incur higher costs. Please see codesandbox.io/pricing for details on specs and costs.
     *
     */
    tier?: 'Pico' | 'Nano' | 'Micro' | 'Small' | 'Medium' | 'Large' | 'XLarge';
};

export type VMStartResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        bootup_type: string;
        cluster: string;
        id: string;
        latest_pitcher_version: string;
        pitcher_manager_version: string;
        pitcher_token: string;
        pitcher_url: string;
        pitcher_version: string;
        reconnect_token: string;
        user_workspace_path: string;
        workspace_path: string;
    };
};

export type VMUpdateHibernationTimeoutRequest = {
    /**
     * The new hibernation timeout in seconds.
     *
     * Must be greater than 0 and less than or equal to 86400 (24 hours).
     *
     */
    hibernation_timeout_seconds: number;
};

export type VMUpdateHibernationTimeoutResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        hibernation_timeout_seconds: number;
        id: string;
    };
};

export type VMUpdateSpecsRequest = {
    /**
     * Determines which specs to update the VM with.
     *
     * Not all tiers will be available depending on the workspace subscription status, and higher tiers incur higher costs. Please see codesandbox.io/pricing for details on specs and costs.
     *
     */
    tier: 'Pico' | 'Nano' | 'Micro' | 'Small' | 'Medium' | 'Large' | 'XLarge';
};

export type VMUpdateSpecsResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        id: string;
        tier: string;
    };
};

export type WorkspaceCreateRequest = {
    /**
     * Name for the new workspace. Maximum length 64 characters.
     */
    name: string;
};

export type WorkspaceCreateResponse = {
    errors?: Array<((string | {
    [key: string]: unknown;
}))>;
    success?: boolean;
} & {
    data?: {
        id: string;
        name: string;
    };
};

export type MetaInfoResponse = (MetaInformation);

export type MetaInfoError = unknown;

export type WorkspaceCreateData = {
    /**
     * Workspace Create Request
     */
    body?: WorkspaceCreateRequest;
};

export type WorkspaceCreateResponse2 = (WorkspaceCreateResponse);

export type WorkspaceCreateError = unknown;

export type TokenCreateData = {
    /**
     * Token Create Request
     */
    body?: TokenCreateRequest;
};

export type TokenCreateResponse2 = (TokenCreateResponse);

export type TokenCreateError = unknown;

export type TokenUpdateData = {
    /**
     * Token Update Request
     */
    body?: TokenUpdateRequest;
};

export type TokenUpdateResponse2 = (TokenUpdateResponse);

export type TokenUpdateError = unknown;

export type SandboxListData = {
    query?: {
        /**
         * Order direction
         */
        direction?: 'asc' | 'desc';
        /**
         * Field to order results by
         */
        order_by?: 'inserted_at' | 'updated_at';
        /**
         * Page number to return
         */
        page?: number;
        /**
         * Maximum number of sandboxes to return in a single response
         */
        page_size?: number;
        /**
         * Comma-separated list of tags to filter by
         */
        tags?: string;
    };
};

export type SandboxListResponse2 = (SandboxListResponse);

export type SandboxListError = unknown;

export type SandboxCreateData = {
    /**
     * Sandbox Create Request
     */
    body?: SandboxCreateRequest;
};

export type SandboxCreateResponse2 = (SandboxCreateResponse);

export type SandboxCreateError = unknown;

export type SandboxGetData = {
    path: {
        /**
         * Short ID of the sandbox to retrieve
         */
        id: string;
    };
};

export type SandboxGetResponse2 = (SandboxGetResponse);

export type SandboxGetError = unknown;

export type SandboxForkData = {
    /**
     * Sandbox Fork Request
     */
    body?: SandboxForkRequest;
    path: {
        /**
         * Short ID of the sandbox to fork
         */
        id: string;
    };
};

export type SandboxForkResponse2 = (SandboxForkResponse);

export type SandboxForkError = unknown;

export type VmHibernateData = {
    /**
     * VM Hibernate Request
     */
    body?: VMHibernateRequest;
    path: {
        /**
         * Sandbox ID
         */
        id: string;
    };
};

export type VmHibernateResponse = (VMHibernateResponse);

export type VmHibernateError = unknown;

export type VmUpdateHibernationTimeoutData = {
    /**
     * VM Update Hibernation Timeout Request
     */
    body?: VMUpdateHibernationTimeoutRequest;
    path: {
        /**
         * Sandbox ID
         */
        id: string;
    };
};

export type VmUpdateHibernationTimeoutResponse = (VMUpdateHibernationTimeoutResponse);

export type VmUpdateHibernationTimeoutError = unknown;

export type VmShutdownData = {
    /**
     * VM Shutdown Request
     */
    body?: VMShutdownRequest;
    path: {
        /**
         * Sandbox ID
         */
        id: string;
    };
};

export type VmShutdownResponse = (VMShutdownResponse);

export type VmShutdownError = unknown;

export type VmUpdateSpecsData = {
    /**
     * VM Update Specs Request
     */
    body?: VMUpdateSpecsRequest;
    path: {
        /**
         * Sandbox ID
         */
        id: string;
    };
};

export type VmUpdateSpecsResponse = (VMUpdateSpecsResponse);

export type VmUpdateSpecsError = unknown;

export type VmStartData = {
    /**
     * VM Start Request
     */
    body?: VMStartRequest;
    path: {
        /**
         * Sandbox ID
         */
        id: string;
    };
};

export type VmStartResponse = (VMStartResponse);

export type VmStartError = unknown;

export type VmUpdateSpecs2Data = {
    /**
     * VM Update Specs Request
     */
    body?: VMUpdateSpecsRequest;
    path: {
        /**
         * Sandbox ID
         */
        id: string;
    };
};

export type VmUpdateSpecs2Response = (VMUpdateSpecsResponse);

export type VmUpdateSpecs2Error = unknown;